version: "3.9"

services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "(cd /game && lake update && lake build) && npm start"
    volumes:
      - ..:/game
    ports:
      - "3000:3000"
